name: golangci-lint

on: [ push ]
jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Go via go.mod
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          check-latest: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.4