name: test

on: [ push, pull_request ]
jobs:
  test:
    strategy:
      matrix:
        go: [
          '1.19',
          '1.20',
        ]
        os: [
          ubuntu-latest,
          macos-latest,
          windows-latest,
        ]

    runs-on: ${{ matrix.os }}

    env:
      OS: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Go ${{ matrix.go }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
          check-latest: true
          cache: true
      - name: Test
        run: go test -v -race -coverprofile="coverage.txt" -covermode=atomic ./...
      - name: Upload code coverage
        uses: codecov/codecov-action@v3
        if: matrix.go == '1.20'
        with:
          file: coverage.txt
          env_vars: OS

